### ISSUE TITLE
How do i use it ?

### ISSUE THREAD

**Issue by Tedeee** [ShyykoSerhiy/canvas-png-compression#4]
var url = this.canvas.toDataURL();

here is my code , it said replace the toDataURL , so how do i pass in the this canvas ? 

this.canvas.CanvasPngCompression.replaceToDataURL();

CanvasPngCompression.replaceToDataURL(this.canvas);

both tested is not working, can i ask how to mke it work ? thank

**Comment by ShyykoSerhiy** [comment]
CanvasPngCompression.replaceToDataURL() changes HTMLCanvasElement.prototype.toDataURL 
so you should be able to use second parameter:
```js
CanvasPngCompression.replaceToDataURL()
this.canvas.toDataURL('image/png', 0.1);
```
you can refer to https://github.com/ShyykoSerhiy/canvas-png-compression/blob/master/demo/demo.html as an example.

**Comment by ShyykoSerhiy** [comment]
you can run the demo via
```sh
npm i
node ./server.js
```
then open http://localhost:3000/demo/demo.html

**Comment by ShyykoSerhiy** [comment]
Closing
